### ISSUE TITLE
The asset `hotwire_spark.js` was not found in the load path

### ISSUE THREAD

**Issue by JuzerShakir** [basecamp/hotwire-spark#16]
Adding this gem to the `development` group of my Gemfile, running `bundle`, and then running `bin/dev` results in the following error:

```
Propshaft::MissingAssetError (The asset 'hotwire_spark.js' was not found in the load path.):
```

<details><summary>Here's the full error trace:</summary>
<p>

```
[propshaft (1.1.0) lib/propshaft/helper.rb:4:in `compute_asset_path'](http://localhost:3000/#)
[actionview (8.0.1) lib/action_view/helpers/asset_url_helper.rb:204:in `asset_path'](http://localhost:3000/#)
[hotwire-spark (40a26cd3b60e) lib/hotwire/spark/middleware.rb:36:in `script_tag'](http://localhost:3000/#)
[hotwire-spark (40a26cd3b60e) lib/hotwire/spark/middleware.rb:32:in `inject_javascript'](http://localhost:3000/#)
[hotwire-spark (40a26cd3b60e) lib/hotwire/spark/middleware.rb:11:in `call'](http://localhost:3000/#)
[rack (3.1.8) lib/rack/tempfile_reaper.rb:20:in `call'](http://localhost:3000/#)
[rack (3.1.8) lib/rack/etag.rb:29:in `call'](http://localhost:3000/#)
[rack (3.1.8) lib/rack/conditional_get.rb:31:in `call'](http://localhost:3000/#)
[rack (3.1.8) lib/rack/head.rb:15:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/http/permissions_policy.rb:38:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/http/content_security_policy.rb:38:in `call'](http://localhost:3000/#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'](http://localhost:3000/#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/cookies.rb:706:in `call'](http://localhost:3000/#)
[activerecord (8.0.1) lib/active_record/migration.rb:671:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'](http://localhost:3000/#)
[activesupport (8.0.1) lib/active_support/callbacks.rb:100:in `run_callbacks'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/callbacks.rb:30:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/executor.rb:16:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'](http://localhost:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'](http://localhost:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'](http://localhost:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'](http://localhost:3000/#)
[railties (8.0.1) lib/rails/rack/logger.rb:41:in `call_app'](http://localhost:3000/#)
[railties (8.0.1) lib/rails/rack/logger.rb:29:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/request_id.rb:34:in `call'](http://localhost:3000/#)
[rack (3.1.8) lib/rack/method_override.rb:28:in `call'](http://localhost:3000/#)
[rack (3.1.8) lib/rack/runtime.rb:24:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/server_timing.rb:60:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/executor.rb:16:in `call'](http://localhost:3000/#)
[hotwire-spark (40a26cd3b60e) lib/hotwire/spark/action_cable/persistent_cable_middleware.rb:12:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/static.rb:27:in `call'](http://localhost:3000/#)
[rack (3.1.8) lib/rack/sendfile.rb:114:in `call'](http://localhost:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/host_authorization.rb:143:in `call'](http://localhost:3000/#)
[railties (8.0.1) lib/rails/engine.rb:535:in `call'](http://localhost:3000/#)
[puma (6.5.0) lib/puma/configuration.rb:279:in `call'](http://localhost:3000/#)
[puma (6.5.0) lib/puma/request.rb:99:in `block in handle_request'](http://localhost:3000/#)
[puma (6.5.0) lib/puma/thread_pool.rb:389:in `with_force_shutdown'](http://localhost:3000/#)
[puma (6.5.0) lib/puma/request.rb:98:in `handle_request'](http://localhost:3000/#)
[puma (6.5.0) lib/puma/server.rb:468:in `process_client'](http://localhost:3000/#)
[puma (6.5.0) lib/puma/server.rb:249:in `block in run'](http://localhost:3000/#)
[puma (6.5.0) lib/puma/thread_pool.rb:166:in `block in spawn_thread'](http://localhost:3000/#)
```

</p>
</details> 

I am using TailwindCSS for styling with `cssbundling-rails`, and `esbuild` with `jsbundling-rails` with these version:
`cssbundling-rails (1.4.1)`
`jsbundling-rails (1.3.1)`
`rails (8.0.1)`
`ruby (3.3.6)`

I also tried using the code from the `main` branch but it results in same.

**Comment by jorgemanrubia** [comment]
Hmm I think that path should be included by default, but I created a patch to make sure it's included here https://github.com/basecamp/hotwire-spark/pull/20. Would you mind giving it a try with that branch to see if the problem gets fixed @JuzerShakir?

**Comment by jacob-carlborg-apoex** [comment]
@JuzerShakir I suggest you run `Rails.application.config.assets.paths` and see if hotwire-spark is included among the asset paths.

**Comment by JuzerShakir** [comment]
Running `Rails.application.config.assets.paths` returns:

```
["../app/assets/builds",
 "../app/assets/images",
 "../app/assets/stylesheets",
 "/../ruby-3.3.6/gems/turbo-rails-2.0.11/app/assets/javascripts",
 "/../ruby-3.3.6/gems/stimulus-rails-1.3.4/app/assets/javascripts",
 "/../ruby-3.3.6/gems/actioncable-8.0.1/app/assets/javascripts",
 "/../ruby-3.3.6/gems/actiontext-8.0.1/app/assets/javascripts",
 "/../ruby-3.3.6/gems/actiontext-8.0.1/app/assets/stylesheets",
 "/../ruby-3.3.6/gems/activestorage-8.0.1/app/assets/javascripts",
 "/../ruby-3.3.6/gems/actionview-8.0.1/app/assets/javascripts"] 
```

**Comment by JuzerShakir** [comment]
> Could you try to prepare a minimal repo reproducing the issue?

I tried initiating a couple of new rails applications, one with the `tailwindcss` & the other with `bootstrap`. (Since mine uses `bootstrap`, I just wanted to make sure whether this was related to the CSS library)

```
rails new test_hotwire-spark -c bootstrap -j esbuild -a propshaft --skip-test
```

```
rails new test_hotwire-spark -c tailwindcss -j esbuild -a propshaft --skip-test
```

After adding the `hotwire_spark` library to it, and running the `bin/dev` command it doesn't show the error we are looking for and yes the changes are reflected in real-time. (Tested only with HTML)

Both apps were initialized with the same version of Ruby, Rails, `jsbundling-rails`, `cssbundling-rails`, `propshaft` & `hotwire-spark`. Yet one shows the errors while the other doesn't!

> I'm puzzled about what can be going on here.

Indeed! @jorgemanrubia 😭 

The app I am getting the error from is the one I previously initialized with the older version of Rails (v7) and other libraries. I recently upgraded my app to Rails v8 and all the other libraries with it and also js packages. So it could be that upgrading an app from the previous version to the new one might cause the issue. It's an edge-case scenario to think of!

**Comment by JuzerShakir** [comment]
@jorgemanrubia The issue has been resolved and guess what did the trick? 😄 

```
rails assets:clobber
rails assets:precompile
```

Wish I had done this earlier and this would have saved so much of our time.
But let this be a lesson to all other developers who could face this similar issue in the future.

Thanks a lot, @jorgemanrubia & @jacob-carlborg-apoex for your instant assistance! 🤝

**Comment by JuzerShakir** [comment]
@jorgemanrubia The issue has been resolved and guess what did the trick? 😄 

```
rails assets:clobber
rails assets:precompile
```

Wish I had done this earlier and this would have saved so much of our time.
But let this be a lesson to all other developers who could face this similar issue in the future.

Thanks a lot, @jorgemanrubia & @jacob-carlborg-apoex for your instant assistance! 🤝

**Comment by jorgemanrubia** [comment]
Wonderful. Thanks for the follow up!
